### ISSUE TITLE
[Request] Enhance UI Clarity with Revised Icons and Button Placement

### ISSUE THREAD

**Issue by Strawlrus** [CmdrCody51/OctoPrint-MarlinSlider#5]
### Is your feature request related to a problem? Please describe.

Yes, the feature request is related to a usability concern. Specifically, the user is expressing confusion about the current representation of the "Check" symbol as the button to query the current percentage in the OctoPrint plugin. The request suggests replacing the "Check" symbol with a more intuitive "Question Mark" and potentially relocating the check button to improve clarity and the overall user experience.

### Describe the solution you'd like

Hi there!

Firstly, kudos on the fantastic work with your plugin, which has significantly enhanced the usability and visual appeal of OctoPrint. Thank you for that!

I wanted to share a suggestion regarding the user interface. I've noticed that the "Check" symbol is used as the button to query the current percentage, and I find it a bit confusing at times. To enhance clarity, I propose replacing the "Check" symbol with something more intuitive, like a "Question Mark" symbol.

Additionally, it might be beneficial to consider relocating the save button to a separate check mark. Placing it to the right of the "FeedSet" or "FlowSet" fields could help streamline the user experience.

Thanks for considering this enhancement! Looking forward to seeing more great updates from your end.

**Comment by CmdrCody51** [comment]
I have found that, historically, the Question mark is used as a Help symbol in OctoPrint.
I agree a little more spacing between the checkmark and the Send/Display would be better.
Maybe 'Query' (with a little printer icon?) bigger space and then 'Set Xxxxrate:###' button?
This will be updated after my next plugin comes out. (Spring 2024)
